<a href="https://colab.research.google.com/github/Merlin-Sudha/Numpy--and--Pandas/blob/main/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python DA Assignment 1—Numpy and Pandas

# Numpy Array Operations:

In [ ]:
import numpy as np

# 1. Create a 1D NumPy array for Week 1
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
# 2. Inspection and properties
print("Week 1 Temperatures:", temperatures_w1)
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Shape: (7,)
Data type: float64
Number of elements: 7

In [ ]:
# 3. Array operations
# Convert Celsius to Fahrenheit
temperatures_f = (temperatures_w1 * 9/5) + 32
print("\nTemperatures in Fahrenheit:", temperatures_f)

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [ ]:
# Find maximum, minimum, and mean
print("Maximum temperature:", temperatures_w1.max())
print("Minimum temperature:", temperatures_w1.min())
print("Mean temperature:", temperatures_w1.mean())

Maximum temperature: 26.1
Minimum temperature: 20.8
Mean temperature: 23.542857142857144

In [ ]:
# 4. Array slicing and indexing
print("\nFirst three days:", temperatures_w1[:3])
print("Weekend temperatures:", temperatures_w1[-2:])
print("Middle three days:", temperatures_w1[2:5])

First three days: [22.5 25.3 20.8]
Weekend temperatures: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

In [ ]:
# 5. Create a 2D NumPy array for two weeks
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

In [ ]:
# 6. Inspect and slice the 2D array
print("\n2D Temperature Array:")
print(temperatures)
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

# Extract temperatures for each week
week1 = temperatures[0]
week2 = temperatures[1]
print("\nWeek 1 temperatures:", week1)
print("Week 2 temperatures:", week2)

# Extract weekend temperatures (last two days) for both weeks
weekends = temperatures[:, -2:]
print("\nWeekend temperatures for both weeks:")
print(weekends)

2D Temperature Array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]
Shape: (2, 7)
Data type: float64
Total number of elements: 14

Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend temperatures for both weeks:
[[24.8 21.9]
 [22.8 20.1]]

# Pandas Series:

In [ ]:
import pandas as pd

# 1. Creating Pandas Series

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)

print("Marks Series:")
print(marks)

Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [ ]:
# 2. Indexing and Slicing

# Access the mark of the 1st rank student using integer index
print("\nMark of 1st Rank Student:")
print(marks[0])

# Retrieve the marks of the top 3 ranks using loc
print("\nTop 3 Rank Marks (using loc):")
print(marks.loc["Rank1":"Rank3"])

# Retrieve the mark of the 3rd-ranked student using iloc
print("\nMark of 3rd Rank Student (using iloc):")
print(marks.iloc[2])

# Boolean mask: Marks greater than 90
print("\nMarks Greater Than 90:")
print(marks[marks > 90])

Mark of 1st Rank Student:
95

Top 3 Rank Marks (using loc):
Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of 3rd Rank Student (using iloc):
89

Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64

/tmp/ipykernel_1524/915602934.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])

In [ ]:
# 3. Manipulating Series

# Modify the mark of the 1st rank student
marks["Rank1"] = 100

print("\nAfter Updating Rank1 Marks:")
print(marks)

# Remove the last rank entry
marks = marks.drop("Rank5")

print("\nAfter Removing Rank5:")
print(marks)

# Compute CGPA by dividing marks by 10
cgpa = marks / 10

print("\nCGPA:")
print(cgpa)

After Updating Rank1 Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After Removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

# Pandas DataFrame:

In [ ]:
import pandas as pd

# 1. Creating Pandas DataFrame

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": [
        "Electronics", "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"
    ],
    "Region": [
        "North", "South", "North", "East", "West",
        "North", "East", "West", "South", "North"
    ],
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print("Transactions DataFrame:")
df = pd.DataFrame(transactions)
print(transactions)

Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
# 2. Data Exploration

df.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [ ]:
df.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
df.sample()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200

In [ ]:
df.shape

(10, 4)

In [ ]:
df.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [ ]:
df.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

       TransactionID      Amount
count       10.00000   10.000000
mean       105.50000  278.000000
std          3.02765   99.755256
min        101.00000  150.000000
25%        103.25000  200.000000
50%        105.50000  275.000000
75%        107.75000  337.500000
max        110.00000  450.000000

In [ ]:

 #Display only the 'ProductCategory' and 'Amount' columns.

print(df[["ProductCategory","Amount"]]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
#Retrieve the last 3 columns of the DataFrame using iloc or loc.

print(df.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
#Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

print(df[(df["Region"] == "North") &
                   (df["Amount"] > 200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
#Find the value counts for the 'ProductCategory' column.

print(df["ProductCategory"].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
#Find the unique values in the 'Region' column.

print(df["Region"].unique())

['North' 'South' 'East' 'West']

In [ ]:
# Group by 'Region' and find the mean amount for each region.

print(df.groupby("Region")["Amount"].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [ ]:
#3. Manipulating the DataFrame:

#Modify the 'Amount' for the transaction with TransactionID 102 to 165.

df.loc[transactions["TransactionID"] == 102, "Amount"] = 165
print(df)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400